language: minimal

services:
  - docker

install:
  - docker pull jjmerelo/test-perl6
  - docker images

script: docker run -t -v  $TRAVIS_BUILD_DIR:/test --entrypoint="/bin/sh" jjmerelo/test-perl6 -c "apk add --update --no-cache make gcc linux-headers && ls /usr/include/linux/term* && zef build . && zef test ."

