name: Windows test
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          if not exist "C:\rakudo" cinst rakudostar
          SET PATH=C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;%PATH%
          refreshenv
          perl6 -v
