name: Windows test
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          cinst rakudostar
          cinst mingw
          $env:Path = "C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;$env:Path"
          refreshenv
          get-command cc.exe
          get-command gcc.exe
          get-command make.exe
          zef build . --verbose
